# Generated by Django 5.2.15 on 2026-06-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.PositiveIntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='carrera.carrera')),
                ('profesores', models.ManyToManyField(blank=True, related_name='materias', to='profesor.profesor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
